apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musicguessr-ingress
  namespace: musicguessr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - musicguessr.app
      secretName: musicguessr-tls
  rules:
    - host: musicguessr.app
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: musicguessr-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musicguessr-frontend
                port:
                  number: 80
